apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: cloudevent-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - env:
        - name: EVENT_SINK
          value: https://test.x.pipedream.net/
        - name: EVENT_SOURCE
          value: thisgithub/repo
        image: index.docker.io/iancoffey/gateway-0ff5cc7683397869eb157e054201775b@sha256:c1bf46115f3691907b2b3f31457523aa20d0c1d4cf5d718ee1c6797aadb52c42
        name: gateway-server
        ports:
        - containerPort: 8089

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: cloudevent-gateway-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8089
  selector:
    app: gateway
  type: Loadbalancer

---
